### ISSUE TITLE
Hi, I want to ask why the snake needs to reverse the direction?

### ISSUE THREAD

**Issue by one-thinking-reed** [aryaminus/srijana#1]

**Comment by aryaminus** [comment]
Nothing major, Just giving control to all the arrow keys. Close the issue if you don't have further question

**Comment by one-thinking-reed** [comment]
Sorry to bother you, but I don't want the snake exchange its head and tail, I tried to change the code but it cannot work.
And may I ask what's the maximum length of the snake using your code?



---Original---

**Comment by aryaminus** [comment]
Damn, never thought about the maximum length, the exchange of head and tail is there to prevent it from not having any space to move, and not allowing it to exchange, will need some changes in [here](https://github.com/aryaminus/srijana/blob/master/main.cpp#L382)  [here](https://github.com/aryaminus/srijana/blob/master/main.cpp#L441), basically the `dir` variable
